name: Package Tests

on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  macos:
    if: ${{ !(github.event.pull_request.draft || false) }}
    strategy:
      fail-fast: false
      matrix:
        swift-config:
          - { xcode_version: "15.0.1", macos_version: 14 }
          - { xcode_version: "15.2", macos_version: 14 }
          - { xcode_version: "15.4", macos_version: 14 }
          - { xcode_version: "16.1", macos_version: 14 }
          - { xcode_version: "16.2", macos_version: 14 }
          - { xcode_version: "15.4", macos_version: 15 }
          - { xcode_version: "16.1", macos_version: 15 }
          - { xcode_version: "16.3", macos_version: 15 }
    runs-on: macos-${{ matrix.swift-config.macos_version }}
    name: Xcode ${{ matrix.swift-config.xcode_version }} - macOS ${{ matrix.swift-config.macos_version }}
    steps:
    - uses: actions/checkout@v4
    - name: Check Swift version
      run: |
        sudo xcode-select -s /Applications/Xcode_${{ matrix.swift-config.xcode_version }}.app/
        export TOOLCHAINS=swift
        swift --version
    - name: Run tests
      run: swift test

  linux:
    if: ${{ !(github.event.pull_request.draft || false) }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        swift-config:
          - { version: "5.7", distro: amazonlinux2 }
          - { version: "5.7", distro: jammy }
          - { version: "5.7", distro: focal }
          - { version: "5.7", distro: bionic }
          - { version: "5.7", distro: centos7 }
          - { version: "5.8", distro: amazonlinux2 }
          - { version: "5.8", distro: rhel-ubi9 }
          - { version: "5.8", distro: focal }
          - { version: "5.8", distro: jammy }
          - { version: "5.8", distro: centos7 }
          - { version: "5.8", distro: bionic }
          - { version: "5.9", distro: amazonlinux2 }
          - { version: "5.9", distro: rhel-ubi9 }
          - { version: "5.9", distro: focal }
          - { version: "5.9", distro: jammy }
          - { version: "5.9", distro: centos7 }
          - { version: "5.10", distro: bookworm }
          - { version: "5.10", distro: amazonlinux2 }
          - { version: "5.10", distro: rhel-ubi9 }
          - { version: "5.10", distro: noble }
          - { version: "5.10", distro: fedora39 }
          - { version: "5.10", distro: focal }
          - { version: "5.10", distro: jammy }
          - { version: "5.10", distro: mantic }
          - { version: "5.10", distro: centos7 }
          - { version: "6.0.3", distro: bookworm }
          - { version: "6.0.3", distro: amazonlinux2 }
          - { version: "6.0.3", distro: rhel-ubi9 }
          - { version: "6.0.3", distro: focal }
          - { version: "6.0.3", distro: jammy }
          - { version: "6.1.0", distro: bookworm }
          - { version: "6.1.0", distro: amazonlinux2 }
          - { version: "6.1.0", distro: rhel-ubi9 }
          - { version: "6.1.0", distro: focal }
          - { version: "6.1.0", distro: jammy }
    container: swift:${{ matrix.swift-config.version }}-${{ matrix.swift-config.distro }}
    name: Swift ${{ matrix.swift-config.version }} - ${{ matrix.swift-config.distro }}
    steps:
    - uses: actions/checkout@v1
    - name: Run ${{ matrix.swift-config.version }} - ${{ matrix.swift-config.distro }} Tests
      run: swift test
